### ISSUE TITLE
tagFormat not respected

### ISSUE THREAD

**Issue by sinedied** [RimacTechnology/semantic-release-monorepo#2]
### Issues

- [X] I have checked [existing issues](https://github.com/RimacTechnology/semantic-release-monorepo/issues) and there are no issues with the same problem.

### `semantic-release-monorepo` Version You Are Using

1.1.4

### Your Config

```
  "release": {
    "extends": [
      "semantic-release-npm-github"
    ],
    "tagFormat": "cli-${version}",
    "branches": "main"
  },
  ```

### Steps to reproduce

Git clone this project, and replace semantic-release-monorepo with your version.
Update the config to the one above, and run:

```
cd packages/cli
semantic-release-monorepo --dry-run
```

It cannot find existing tags "cli-x.x.x" as it searches for "<packageName>@x.x.x" tags. 

### Expected behavior

Specified tag format is respected.

Thanks for making this fork BTW it worked out of the box except for this tag issue.

### Actual behavior

It forces the tag format "<packageName>@x.x.x"

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by mario-jerkovic** [comment]
Hi @sinedied 👋
thanks for posting the issue. Will take a look and open a PR for this

**Comment by mario-jerkovic** [comment]
@sinedied 
New package version has been [released](https://github.com/RimacTechnology/semantic-release-monorepo/releases/tag/v1.1.5) 🍻.
