### ISSUE TITLE
Ability to declare dependencies within release config file

### ISSUE THREAD

**Issue by johanneslumpe** [RimacTechnology/semantic-release-monorepo#5]
### Issues

- [X] I have checked [existing issues](https://github.com/RimacTechnology/semantic-release-monorepo/issues) and there are no existing ones with the same request.

### Feature description

I'm curious if you'd be open to a PR that adds the ability to declare a list of dependencies in an application's release config file. We have a use case where we have some top level folders in our mono repo which should trigger a version bump of an application, e.g.

```
- some-folder
- another-folder
- my-app
```
`my-app` imports files from both `some-folder` and `another-folder` and changes to those folders have to be included in the commits that trigger version bumps of `my-app`.

I have a patch ready for this if you'd be open to include this as a feature, which enables users to define dependencies in the above example like this:
```
// .releaserc.cjs in `my-app`

module.exports = {
 // other config
dependencies: ['some-folder', 'another-folder']
};

**Comment by mario-jerkovic** [comment]
Hello @johanneslumpe 👋

Thank you for reaching out and for your interest in contributing to the project! We are always open to new ideas and pull requests from the community.

Regarding this particular issue, we are aware of the need to handle dependencies within a monorepo setup. We encounter this situation from time to time and have been using some workarounds to trigger releases 😅. Your suggestion to declare a list of dependencies in the application's release config file is certainly a valid approach.

Currently, I am planning to address this by reading the app's  package.json and checking if the changes made to the project affect any dependencies that the application being released relies on. This way, we can ensure that changes trigger the appropriate version bumps without requiring additional configuration, making the process more seamless.

However, I am open to considering your approach if it provides a better solution or if it addresses use cases that my planned approach might miss 🙂

As a side note, I am currently on vacation and will be able to push this feature in ~1 week 🏝️.

Thank you for your contribution and for helping to improve the project! 🍻

**Comment by johanneslumpe** [comment]
@mario-jerkovic That sounds logical to me for JS/TS based projects. We also have applications in other languages, for which we would like to reuse the same solution. Currently I'm creating a dummy `package.json` file to get around the issue with a project's name being sourced from it.

I think having the ability to automatically resolve file-dependencies from a package file is a good default to have, if there is a way to extend it or replace it. What do you think about an approach where this is pluggable? In the most basic sense this could just be that the release config allows users to specify a dependency resolver function/strategy for the project they're trying to release. The default could be the package.json resolver strategy you mentioned, which could crawl the package.json for `file://` dependencies and add those to the list of paths to check. There might still be edge cases where you have a file dependency but you do not necessarily want to include it as a trigger for a version bump (for whatever reason).

A resolver/strategy based approach would also work for resolving the project name, making it easier to integrate with other languages/tooling.

Let me know your thoughts and enjoy your vacation!

**Comment by mario-jerkovic** [comment]
@johanneslumpe I totally agree and you are right, my initial suggestion was more focused on TS/JS-based projects. I appreciate the broader perspective you're bringing in! What do you think about enhancing the `.releaserc` file with a `dependencies key? This could include a resolver function that would accept two arguments:

1. **packagePath** (or perhaps **packageJSON**) from the workspace where the release is being triggered.
2. An array of commits in the following format:

```json 
[
    {
        "commit": {
            "long": "long-commit-hash",
            "short": "short-commit-hash"
        },
        "tree": {
            "long": "long-tree-hash",
            "short": "short-tree-hash"
        },
        "author": {
            "name": "Author Name",
            "email": "author@example.com",
            "date": "2024-08-12T11:12:05.000Z"
        },
        "committer": {
            "name": "Committer Name",
            "email": "committer@example.com",
            "date": "2024-08-12T11:12:05.000Z"
        },
        "subject": "Commit message subject",
        "body": "",
        "hash": "commit-hash",
        "committerDate": "2024-08-12T11:12:05.000Z",
        "message": "Full commit message",
        "gitTags": "(HEAD -> branch-name, origin/branch-name)"
    }
]
```

For example, if you are using Yarn as your package manager, you could list all workspaces with `yarn workspaces list --json`, and then check if the commit path matches one of the workspace paths as previously mentioned yarn command returns this:
```json
{"location":"apps/app1","name":"@org/app1"}
{"location":"apps/app2","name":"@org/app2"}
```
 From there, you could determine if it's in your dependencies or devDependencies list. This function could be quite flexible, allowing you to implement custom logic depending on your project's needs—even if you're using **semantic-release-monorepo** in a different language.

I acknowledge that this approach isn't perfect in the sense that it doesn't automatically resolve dependencies within a nested dependency tree (e.g., if Workspace 3 is a dependency of Workspace 2, which is a dependency of Workspace 1). However, I think this could be a solid starting point without diving too deep into the complexity of dependency trees. Just wanted to share this idea for now 😄

Looking forward to hearing your thoughts!

**Comment by mario-jerkovic** [comment]
> @mario-jerkovic That makes sense to me! That's actually more powerful than what I had in mind. Allowing fully custom logic to determine the additional commits that should be included in version computation should work well I think, definitely better than just returning a list of dependency paths and have hard-coded filter logic. 😄

Thank you! 😊 I wasn’t entirely sure if we were on the same page, but it turns out we were! 😄 This PR is currently published as an [alpha version](https://www.npmjs.com/package/@rimac-technology/semantic-release-monorepo/v/1.2.0-alpha.1). I'll be testing it in my repositories tomorrow, and if everything goes smoothly, I’ll push out a new version.

Also, a big thanks for pointing out this issue—it really helped improve the implementation!
